[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Posts"
pageRef = "/posts/"
weight = 20

[[main]]
pageRef = "About"
weight = 25

[[main]]
name = "kawr Repo"
url = "https://github.com/SharktoothActual/kawr"
weight = 30
