baseURL = 'https://sharktoothactual.github.io/website/'
locale = 'en-us'
title = "Shark's Website"
theme = 'ananke'
[params]
  subtitle = 'A very good website (but not always!)'
  mainSections = ["posts"]
  show_recent_posts = true
  [params.contact]
    email = 'shark@sharktooth.meme'
    phone = '+1 111-867-5309'
